const games = [
  "Aladdin (USA).zip",
  "Batman Beyond - Return of the Joker (USA).zip",
  "Blaster Master - Enemy Below (USA, Europe) (SGB Enhanced).zip",
  "Bomberman Max - Blue Champion (USA).zip",
  "Bomberman Max - Red Challenger (USA).zip",
  "Bomberman Quest (USA) (SGB Enhanced).zip",
  "Bug's Life, A (USA) (SGB Enhanced).zip",
  "Bust-A-Move 4 (USA, Europe).zip",
  "Bust-A-Move Millennium (USA, Europe).zip",
  "Cannon Fodder (USA) (En,Fr,De,Es,It).zip",
  "Carmageddon - Carpocalypse Now (USA, Europe) (En,Fr,Es,It).zip",
  "Centipede (USA).zip",
  "Chessmaster (USA, Europe).zip",
  "Classic Bubble Bobble (USA) (SGB Enhanced).zip",
  "Colin McRae Rally (Europe).zip",
  "Croc (USA, Europe).zip",
  "Croc 2 (USA, Europe).zip",
  "Crystalis (USA).zip",
  "Driver - You are the Wheelman (USA) (En,Fr,De,Es,It).zip",
  "Donkey Kong Country (USA, Europe) (En,Fr,De,Es,It).zip",
  "Dragon Ball Z - Legendary Super Warriors (USA).zip",
  "Dragon Warrior I & II (USA) (SGB Enhanced).zip",
  "Dragon Warrior III (USA).zip",
  "Dragon Warrior Monsters (USA, Europe) (SGB Enhanced).zip",
  "Duke Nukem (USA) (En,Fr,De,Es,It).zip",
  "Earthworm Jim - Menace 2 the Galaxy (USA, Europe).zip",
  "FIFA 2000 (USA, Europe) (SGB Enhanced).zip",
  "Frogger (USA).zip",
  "Game & Watch Gallery 2 (USA, Europe) (SGB Enhanced).zip",
  "Game & Watch Gallery 3 (USA, Europe) (SGB Enhanced).zip",
  "Gex - Enter the Gecko (USA, Europe).zip",
  "Gex 3 - Deep Pocket Gecko (USA).zip",
  "Ghosts'n Goblins (USA, Europe).zip",
  "Grand Theft Auto (USA).zip",
  "Grand Theft Auto 2 (USA).zip",
  "Harry Potter and the Chamber of Secrets (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,Da).zip",
  "Harry Potter and the Sorcerer's Stone (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi).zip",
  "Harvest Moon 2 GBC (USA) (SGB Enhanced).zip",
  "Heroes of Might and Magic (USA) (En,Fr,De).zip",
  "Indiana Jones and the Infernal Machine (USA, Europe) (En,Fr,De).zip",
  "International Superstar Soccer 2000 (USA).zip",
  "Kirby - Tilt 'n' Tumble (USA).zip",
  "LEGO Racers (USA) (En,Fr,Es).zip",
  "Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev A) (SGB Enhanced).zip",
  "Legend of Zelda, The - Oracle of Ages (USA).zip",
  "Legend of Zelda, The - Oracle of Seasons (USA).zip",
  "Looney Tunes Racing (USA) (En,Fr,De,Es,It,Nl).zip",
  "Madden NFL 2000 (USA, Europe) (SGB Enhanced).zip",
  "Magical Tetris Challenge (USA).zip",
  "Mario Golf (USA).zip",
  "Mario Tennis (USA).zip",
  "Mat Hoffman's Pro BMX (USA, Europe).zip",
  "Mega Man Xtreme (USA, Europe).zip",
  "Mega Man Xtreme 2 (USA, Europe).zip",
  "Metal Gear Solid (USA).zip",
  "Micro Machines 1 and 2 - Twin Turbo (USA, Europe).zip",
  "Mission Impossible (USA) (En,Fr,Es).zip",
  "Monopoly (USA).zip",
  "Mortal Kombat 4 (USA, Europe) (SGB Enhanced).zip",
  "Mr. Driller (USA).zip",
  "Ms. Pac-Man - Special Color Edition (USA) (SGB Enhanced).zip",
  "NBA Jam '99 (USA, Europe).zip",
  "NFL Blitz (USA, Europe) (Rev A).zip",
  "Pac-Man - Special Color Edition (USA) (SGB Enhanced).zip",
  "Perfect Dark (USA, Europe) (En,Fr,De,Es,It) (Rumble Version).zip",
  "Pokemon - Crystal Version (USA, Europe) (Rev A).zip",
  "Pokemon - Gold Version (USA, Europe) (SGB Enhanced).zip",
  "Pokemon - Silver Version (USA, Europe) (SGB Enhanced).zip",
  "Pokemon Pinball (USA) (Rumble Version) (SGB Enhanced).zip",
  "Pokemon Puzzle Challenge (USA).zip",
  "Pokemon Trading Card Game (USA) (SGB Enhanced).zip",
  "Prince of Persia (USA, Europe) (En,Fr,De,Es,It).zip",
  "R-Type DX (USA, Europe).zip",
  "Rampage - World Tour (USA, Europe).zip",
  "Rayman (USA) (En,Fr,De,Es,It,Nl).zip",
  "Rayman 2 - The Great Escape (USA) (En,Fr,De,Es,It).zip",
  "Ready 2 Rumble Boxing (USA) (Rumble Version).zip",
  "Resident Evil Gaiden (USA).zip",
  "Road Rash (USA, Europe).zip",
  "San Francisco Rush 2049 (USA, Europe).zip",
  "Shantae (USA).zip",
  "Simpsons, The - Night of the Living Treehouse of Horror (USA, Europe).zip",
  "Space Invaders (USA, Europe).zip",
  "Spider-Man (USA, Europe).zip",
  "Star Wars Episode I - Racer (USA, Europe) (Rumble Version).zip",
  "Street Fighter Alpha - Warriors' Dreams (USA).zip",
  "Super Mario Bros. Deluxe (USA, Europe) (Rev B).zip",
  "Survival Kids (USA) (SGB Enhanced).zip",
  "Tetris DX (World) (SGB Enhanced).zip",
  "Tomb Raider (USA, Europe) (En,Fr,De,Es,It).zip",
  "Tony Hawk's Pro Skater (USA, Europe).zip",
  "Tony Hawk's Pro Skater 2 (USA, Europe).zip",
  "Turok 2 - Seeds of Evil (USA, Europe) (En,Fr,De,Es).zip",
  "WWF WrestleMania 2000 (USA, Europe).zip",
  "Wario Land 3 (World) (En,Ja).zip",
  "Wario Land II (USA, Europe) (SGB Enhanced).zip",
  "Worms Armageddon (USA) (En,Fr,Es).zip",
  "X-Men - Mutant Academy (USA, Europe) (Rev A).zip",
  "Yu-Gi-Oh! - Dark Duel Stories (USA).zip",
  "007 - The World Is Not Enough (USA, Europe).zip"
];

export default games;