const games = [
  "007 - The World Is Not Enough (USA, Europe).zip",
  "10-Pin Bowling (USA) (Rumble Version).zip",
  "102 Dalmatians - Puppies to the Rescue (USA, Europe).zip",
  "1942 (USA, Europe).zip",
  "3-D Ultra Pinball - Thrillride (USA) (Rumble Version).zip",
  "3D Pocket Pool (Europe) (En,Fr,De,Es,It,Nl).zip",
  "4x4 World Trophy (Europe) (En,Fr,De,Es,It).zip",
  "720 Degrees (USA, Europe).zip",
  "Action Man - Search for Base X (USA, Europe).zip",
  "Adventures of Elmo in Grouchland, The (USA).zip",
  "Adventures of the Smurfs, The (Europe) (En,Fr,De,Es,It,Nl).zip",
  "AirForce Delta (USA).zip",
  "Aladdin (USA).zip",
  "Alfred's Adventure (Europe) (En,Fr,De,Es,It).zip",
  "Alice in Wonderland (USA).zip",
  "Aliens - Thanatos Encounter (USA, Europe).zip",
  "All Star Tennis 2000 (Europe).zip",
  "All-Star Baseball 2001 (USA).zip",
  "Alone in the Dark - The New Nightmare (USA) (En,Fr,Es).zip",
  "Animorphs (USA).zip",
  "Antz (USA) (En,Fr,Es).zip",
  "Antz Racing (USA) (En,Fr,De,Es,It,Nl).zip",
  "Antz World Sportz (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Arcade Hits - Joust & Defender (USA, Europe).zip",
  "Arcade Hits - Moon Patrol & Spy Hunter (USA, Europe).zip",
  "Armada - FX Racers (USA).zip",
  "Armorines - Project S.W.A.R.M. (USA, Europe) (En,De).zip",
  "Army Men (USA, Europe) (En,Fr,De).zip",
  "Army Men - Air Combat (USA, Europe) (En,Fr,De).zip",
  "Army Men - Sarge's Heroes 2 (USA, Europe) (En,Fr,De).zip",
  "Army Men 2 (USA, Europe) (En,Fr,De).zip",
  "Arthur's Absolutely Fun Day! (USA).zip",
  "Asterix & Obelix (Europe) (En,Fr,De,Es).zip",
  "Asterix & Obelix vs Caesar (Europe) (En,Fr,De,Es,Nl).zip",
  "Asterix - Search for Dogmatix (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Asteroids (USA, Europe).zip",
  "Atlantis - The Lost Empire (USA, Europe).zip",
  "Austin Powers - Oh, Behave! (USA).zip",
  "Austin Powers - Welcome to my Underground Lair! (USA).zip",
  "Azure Dreams (USA) (SGB Enhanced).zip",
  "Babe and Friends (USA).zip",
  "Baby Felix - Halloween (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Backgammon (Europe) (En,Fr,De,Es).zip",
  "Ballistic (USA).zip",
  "Barbie - Fashion Pack Games (USA, Europe).zip",
  "Barbie - Magic Genie Adventure (USA).zip",
  "Barbie - Ocean Discovery (USA).zip",
  "Barbie - Pet Rescue (USA).zip",
  "Barbie - Shelly Club (Europe) (En,Fr,De,Es,It).zip",
  "Barca Total 2000 (Europe) (En,Fr,De,Es,It,Nl,Ca).zip",
  "Bass Masters Classic (USA, Europe).zip",
  "Batman Beyond - Return of the Joker (USA).zip",
  "BattleTanx (USA).zip",
  "Battleship (USA, Europe).zip",
  "Beach'n Ball (Europe) (En,Fr,De,Es,It).zip",
  "Bear in the Big Blue House (USA) (En,Fr,De,Es,It,Nl).zip",
  "Beauty and the Beast - A Board Game Adventure (USA) (SGB Enhanced).zip",
  "Billy Bob's Huntin' 'n' Fishin' (USA, Europe).zip",
  "Bionic Commando - Elite Forces (USA, Australia).zip",
  "Black Bass - Lure Fishing (USA, Europe).zip",
  "Blade (USA, Europe).zip",
  "Blaster Master - Enemy Below (USA, Europe) (SGB Enhanced).zip",
  "Blue's Clues - Blue's Alphabet Book (USA).zip",
  "Boarder Zone (USA).zip",
  "Bob the Builder - Fix it Fun! (USA).zip",
  "Bomberman Max - Blue Champion (USA).zip",
  "Bomberman Max - Red Challenger (USA).zip",
  "Bomberman Quest (USA) (SGB Enhanced).zip",
  "Buffy the Vampire Slayer (USA, Europe).zip",
  "Bug's Life, A (USA) (SGB Enhanced).zip",
  "Bugs Bunny - Crazy Castle 3 (USA, Europe).zip",
  "Bugs Bunny in Crazy Castle 4 (USA).zip",
  "Bust-A-Move 4 (USA, Europe).zip",
  "Bust-A-Move Millennium (USA, Europe).zip",
  "Buzz Lightyear of Star Command (USA, Europe).zip",
  "Caesars Palace II (USA, Europe).zip",
  "Cannon Fodder (USA) (En,Fr,De,Es,It).zip",
  "Carl Lewis Athletics 2000 (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Carmageddon - Carpocalypse Now (USA, Europe) (En,Fr,Es,It).zip",
  "Casper (USA).zip",
  "Caterpillar Construction Zone (USA, Europe).zip",
  "Catwoman (USA).zip",
  "Catz - Your Virtual Petz Palz (USA).zip",
  "Centipede (USA).zip",
  "Championship Motocross 2001 featuring Ricky Carmichael (USA, Europe).zip",
  "Chase H.Q. - Secret Police (USA) (SGB Enhanced).zip",
  "Chessmaster (USA, Europe).zip",
  "Chicken Run (USA, Europe) (En,Fr,De,Es,It).zip",
  "Classic Bubble Bobble (USA) (SGB Enhanced).zip",
  "Colin McRae Rally (Europe).zip",
  "Commander Keen (USA, Europe).zip",
  "Conker's Pocket Tales (USA, Europe) (En,Fr,De) (SGB Enhanced).zip",
  "Cool Bricks (Europe) (En,Fr,De,Es,It).zip",
  "Croc (USA, Europe).zip",
  "Croc 2 (USA, Europe).zip",
  "Cruis'n Exotica (USA).zip",
  "Crystalis (USA).zip",
  "Cubix - Robots for Everyone - Race 'n Robots (USA) (En,Fr,De,Es,It).zip",
  "CyberTiger (USA, Europe).zip",
  "Daffy Duck - Fowl Play (USA, Europe).zip",
  "Dave Mirra Freestyle BMX (USA, Europe).zip",
  "David Beckham Soccer (Europe) (En,Fr,De,Es,It).zip",
  "Deadly Skies (Europe) (En,Fr,De).zip",
  "Deer Hunter (USA).zip",
  "Deja Vu I & II - The Casebooks of Ace Harding (USA).zip",
  "Denki Blocks! (Europe) (En,Fr,De,Es,It).zip",
  "Dexter's Laboratory - Robot Rampage (USA, Europe).zip",
  "Dinosaur (USA).zip",
  "Diva Starz - Mall Mania (USA).zip",
  "Dogz - Your Virtual Petz Palz (USA).zip",
  "Donald Duck - Goin' Quackers (USA) (En,Fr,De,Es,It).zip",
  "Donkey Kong Country (USA, Europe) (En,Fr,De,Es,It).zip",
  "Doug's Big Game (USA).zip",
  "Dracula - Crazy Vampire (USA).zip",
  "Dragon Ball Z - Legendary Super Warriors (USA).zip",
  "Dragon Dance (USA) (SGB Enhanced).zip",
  "Dragon Tales - Dragon Adventures (USA).zip",
  "Dragon Tales - Dragon Wings (USA).zip",
  "Dragon Warrior I & II (USA) (SGB Enhanced).zip",
  "Dragon Warrior III (USA).zip",
  "Dragon Warrior Monsters (USA, Europe) (SGB Enhanced).zip",
  "Dragon Warrior Monsters 2 - Cobi's Journey (USA) (SGB Enhanced).zip",
  "Dragon Warrior Monsters 2 - Tara's Adventure (USA) (SGB Enhanced).zip",
  "Dragon's Lair (USA, Europe) (En,Ja,Fr,De,Es,Zh).zip",
  "Driver - You are the Wheelman (USA) (En,Fr,De,Es,It).zip",
  "Dropzone (Europe).zip",
  "Duke Nukem (USA) (En,Fr,De,Es,It).zip",
  "Dukes of Hazzard, The - Racing for Home (USA).zip",
  "E.T. - The Extra-Terrestrial - Digital Companion (USA).zip",
  "E.T. - The Extra-Terrestrial - Escape from Planet Earth (USA).zip",
  "E.T. - The Extra-Terrestrial and the Cosmic Garden (USA).zip",
  "ECW Hardcore Revolution (USA, Europe).zip",
  "ESPN International Track & Field (USA).zip",
  "ESPN National Hockey Night (USA).zip",
  "Earthworm Jim - Menace 2 the Galaxy (USA, Europe).zip",
  "Elevator Action EX (Europe) (En,Fr,De,Es,It).zip",
  "Elmo's 123s (USA).zip",
  "Elmo's ABCs (USA).zip",
  "Emperor's New Groove, The (USA).zip",
  "European Super League (Europe) (En,Fr,De,Es,It).zip",
  "Evel Knievel (USA).zip",
  "Extreme Ghostbusters (Europe) (En,Fr,De,Es,It,Pt).zip",
  "Extreme Sports with the Berenstain Bears (USA, Europe) (En,Fr,De,Es,It).zip",
  "F-1 World Grand Prix (Europe) (En,Fr,De,Es).zip",
  "F-18 Thunder Strike (USA, Europe).zip",
  "F.A. Premier League Stars 2001, The (Europe).zip",
  "F1 Championship Season 2000 (Europe) (En,Fr,De,Es,It).zip",
  "F1 Racing Championship (Europe) (En,Fr,De,Es,It).zip",
  "F1 World Grand Prix II for Game Boy Color (USA) (En,Fr,De,Es).zip",
  "FIFA 2000 (USA, Europe) (SGB Enhanced).zip",
  "Fish Files, The (Europe) (En,Fr,De,Es,It).zip",
  "Fix & Foxi - Episode 1 Lupo (Europe) (En,Fr,De).zip",
  "Flintstones, The - Burgertime in Bedrock (USA).zip",
  "Flipper & Lopaka (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da).zip",
  "Force 21 (USA) (En,Fr,De).zip",
  "Formula One 2000 (USA).zip",
  "Fort Boyard (Europe) (En,Fr,De,Es,It,Nl,Pt).zip",
  "Freestyle Scooter (Europe).zip",
  "Frogger (USA).zip",
  "Frogger 2 (USA).zip",
  "Galaga - Destination Earth (USA).zip",
  "Game & Watch Gallery 2 (USA, Europe) (SGB Enhanced).zip",
  "Game & Watch Gallery 3 (USA, Europe) (SGB Enhanced).zip",
  "Games Frenzy (Europe) (En,Fr,De).zip",
  "Gex - Enter the Gecko (USA, Europe).zip",
  "Gex 3 - Deep Pocket Gecko (USA).zip",
  "Ghosts'n Goblins (USA, Europe).zip",
  "Gift (Europe).zip",
  "Gobs of Games (USA) (En,Fr,De).zip",
  "Godzilla - The Series (USA) (En,Fr,De).zip",
  "Godzilla - The Series - Monster Wars (USA) (En,Fr,De).zip",
  "Gold and Glory - The Road to El Dorado (USA).zip",
  "Golden Goal (Europe) (En,Fr,De,Es,It,Nl,Sv).zip",
  "Grand Theft Auto (USA).zip",
  "Grand Theft Auto 2 (USA).zip",
  "Gremlins Unleashed (Europe) (En,Fr,De,Es,It,Pt).zip",
  "Grinch, The (USA).zip",
  "Halloween Racer (Europe) (En,Fr,De,Es,It,Pt).zip",
  "Hamtaro - Ham-Hams Unite! (USA).zip",
  "Hands of Time (USA, Europe) (En,Fr,De,Es,It,Nl).zip",
  "Harley-Davidson Motor Cycles - Race Across America (USA).zip",
  "Harry Potter and the Chamber of Secrets (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,Da).zip",
  "Harry Potter and the Sorcerer's Stone (USA, Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi).zip",
  "Harvest Moon 2 GBC (USA) (SGB Enhanced).zip",
  "Harvest Moon 3 GBC (USA).zip",
  "Harvest Moon GB (USA) (SGB Enhanced).zip",
  "Hello Kitty's Cube Frenzy (USA).zip",
  "Hercules - The Legendary Journeys (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Heroes of Might and Magic (USA) (En,Fr,De).zip",
  "Heroes of Might and Magic II (USA) (En,Fr,De).zip",
  "Hexcite - The Shapes of Victory (USA, Europe) (SGB Enhanced).zip",
  "Hole In One Golf (USA) (Rumble Version) (SGB Enhanced).zip",
  "Hollywood Pinball (Europe) (En,Fr,De,It).zip",
  "Holy Magic Century (Europe) (En,Fr,De) (SGB Enhanced).zip",
  "Hot Wheels - Stunt Track Driver (USA, Europe) (SGB Enhanced).zip",
  "Hoyle Card Games (USA).zip",
  "Hoyle Casino (USA).zip",
  "Hugo - Black Diamond Fever (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi).zip",
  "Hugo - The Evil Mirror (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi).zip",
  "Hype - The Time Quest (Europe) (En,Fr,De,Es,It,Nl,Sv,Da).zip",
  "Indiana Jones and the Infernal Machine (USA, Europe) (En,Fr,De).zip",
  "Inspector Gadget - Operation Madkactus (USA).zip",
  "International Karate 2000 (Europe).zip",
  "International Rally (USA) (SGB Enhanced).zip",
  "International Superstar Soccer 2000 (USA).zip",
  "International Superstar Soccer 99 (USA) (SGB Enhanced).zip",
  "International Track & Field (USA) (SGB Enhanced).zip",
  "Jeff Gordon XS Racing (USA).zip",
  "Jeremy McGrath Supercross 2000 (USA, Europe).zip",
  "Jimmy White's Cueball (Europe).zip",
  "JumpStart Dino Adventure - Field Trip (USA).zip",
  "Jungle Book, The - Mowgli's Wild Adventure (USA) (En,Fr,De,Es,It).zip",
  "Keep the Balance (Europe) (En,Fr,De,Es,It).zip",
  "Kelly Club - Clubhouse Fun (USA).zip",
  "Ken Griffey Jr.'s Slugfest (USA).zip",
  "Kirby - Tilt 'n' Tumble (USA).zip",
  "Kirikou (Europe) (En,Fr,De,Es,It,Pt).zip",
  "Klax (USA, Europe).zip",
  "Klustar (USA).zip",
  "Knockout Kings (USA, Europe).zip",
  "Konami GB Collection Vol.1 (Europe).zip",
  "Konami GB Collection Vol.2 (Europe).zip",
  "Konami GB Collection Vol.3 (Europe).zip",
  "Konami GB Collection Vol.4 (Europe).zip",
  "LEGO Alpha Team (USA).zip",
  "LEGO Island 2 - The Brickster's Revenge (USA) (En,Fr,Es).zip",
  "LEGO Racers (USA) (En,Fr,Es).zip",
  "LEGO Stunt Rally (USA).zip",
  "Land Before Time, The (USA).zip",
  "Las Vegas Cool Hand (USA).zip",
  "Laura (Europe) (En,Fr,De,Es,It,Nl,Sv,Da).zip",
  "Laura (USA).zip",
  "Le Mans 24 Hours (Europe) (En,Fr,De,Es,It).zip",
  "Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev A) (SGB Enhanced).zip",
  "Legend of Zelda, The - Oracle of Ages (USA).zip",
  "Legend of Zelda, The - Oracle of Seasons (USA).zip",
  "Legend of the River King 2 (USA) (SGB Enhanced).zip",
  "Legend of the River King GB (USA) (SGB Enhanced).zip",
  "Lemmings (USA).zip",
  "Lil' Monster (USA) (SGB Enhanced).zip",
  "Lion King, The - Simba's Mighty Adventure (USA, Europe).zip",
  "Little Mermaid II, The - Pinball Frenzy (USA) (En,Fr,De,Es,It) (Rumble Version).zip",
  "Little Nicky (USA).zip",
  "Logical (USA).zip",
  "Looney Tunes (USA).zip",
  "Looney Tunes - Carrot Crazy (USA) (En,Fr,Es).zip",
  "Looney Tunes - Twouble! (USA) (En,Fr,Es).zip",
  "Looney Tunes Collector - Alert! (USA) (En,Fr,Es).zip",
  "Looney Tunes Racing (USA) (En,Fr,De,Es,It,Nl).zip",
  "Lucky Luke (USA) (En,Fr,De,Es).zip",
  "Lucky Luke - Desperado Train (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Lufia - The Legend Returns (USA).zip",
  "M&M's Minis Madness (USA).zip",
  "MTV Sports - Pure Ride (USA, Europe).zip",
  "MTV Sports - Skateboarding featuring Andy MacDonald (USA, Europe).zip",
  "MTV Sports - T.J. Lavin's Ultimate BMX (USA, Europe).zip",
  "Madden NFL 2000 (USA, Europe) (SGB Enhanced).zip",
  "Madden NFL 2001 (USA).zip",
  "Madden NFL 2002 (USA).zip",
  "Magi Nation (USA).zip",
  "Magical Drop (USA).zip",
  "Magical Tetris Challenge (USA).zip",
  "Marble Madness (USA, Europe).zip",
  "Mario Golf (USA).zip",
  "Mario Tennis (USA).zip",
  "Marvin Strikes Back! (USA) (En,Fr,Es).zip",
  "Mary-Kate & Ashley - Get a Clue! (USA, Europe).zip",
  "Mary-Kate and Ashley - Crush Course (USA, Europe).zip",
  "Mary-Kate and Ashley - Pocket Planner (USA, Europe).zip",
  "Mary-Kate and Ashley - Winners Circle (USA, Europe).zip",
  "Mask of Zorro, The (USA).zip",
  "Mat Hoffman's Pro BMX (USA, Europe).zip",
  "Matchbox Emergency Patrol (USA, Europe).zip",
  "Maus, Die (Europe) (En,Fr,De,Es).zip",
  "Maya the Bee & Her Friends (Europe) (En,Fr,De,Es).zip",
  "Maya the Bee - Garden Adventures (Europe) (En,Fr,De,Es).zip",
  "Mega Man Xtreme (USA, Europe).zip",
  "Mega Man Xtreme 2 (USA, Europe).zip",
  "Men in Black - The Series (USA, Europe) (SGB Enhanced).zip",
  "Men in Black 2 - The Series (USA) (En,Fr,De).zip",
  "Merlin (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Metal Gear Solid (USA).zip",
  "Metal Walker (USA).zip",
  "Mia Hamm Soccer Shootout (USA).zip",
  "Mickey's Racing Adventure (USA, Europe) (En,Fr,De,Es,It).zip",
  "Mickey's Speedway USA (USA, Europe) (En,Fr,De,Es).zip",
  "Micro Machines 1 and 2 - Twin Turbo (USA, Europe).zip",
  "Micro Machines V3 (USA, Europe).zip",
  "Micro Maniacs (Europe).zip",
  "Microsoft - The 6 in 1 Puzzle Collection Entertainment Pack (USA).zip",
  "Microsoft - The Best of Entertainment Pack (USA).zip",
  "Microsoft Pinball Arcade (USA).zip",
  "Millennium Winter Sports (USA).zip",
  "Missile Command (USA) (Rumble Version).zip",
  "Mission Impossible (USA) (En,Fr,Es).zip",
  "Monkey Puncher (Europe) (SGB Enhanced).zip",
  "Monopoly (USA).zip",
  "Monster Rancher Battle Card GB (USA) (SGB Enhanced).zip",
  "Monster Rancher Explorer (USA).zip",
  "Monsters, Inc. (USA, Europe).zip",
  "Montezuma's Return! (USA) (En,Es).zip",
  "Moomin's Tale (Europe) (En,Fr,De).zip",
  "Moorhen 3 - The Chicken Chase! (Europe) (En,Fr,De,Es,It).zip",
  "Mortal Kombat 4 (USA, Europe) (SGB Enhanced).zip",
  "Motocross Maniacs 2 (USA).zip",
  "Mr Nutz (USA) (En,Fr,Es).zip",
  "Mr. Driller (USA).zip",
  "Ms. Pac-Man - Special Color Edition (USA) (SGB Enhanced).zip",
  "Mummy Returns, The (USA).zip",
  "Mummy, The (USA).zip",
  "Muppets, The (USA).zip",
  "N.Y. Race (Europe) (En,Fr,De,Es,It,Pt).zip",
  "NASCAR 2000 (USA, Europe).zip",
  "NASCAR Challenge (USA) (Rumble Version).zip",
  "NASCAR Heat (USA).zip",
  "NASCAR Racers (USA).zip",
  "NBA 3 on 3 featuring Kobe Bryant (USA) (SGB Enhanced).zip",
  "NBA Hoopz (USA).zip",
  "NBA In the Zone (USA) (Rev A) (SGB Enhanced).zip",
  "NBA In the Zone 2000 (USA).zip",
  "NBA Jam '99 (USA, Europe).zip",
  "NBA Jam 2001 (USA, Europe).zip",
  "NBA Show Time - NBA on NBC (USA).zip",
  "NFL Blitz (USA, Europe) (Rev A).zip",
  "NFL Blitz 2000 (USA).zip",
  "NFL Blitz 2001 (USA).zip",
  "NHL 2000 (USA, Europe) (SGB Enhanced).zip",
  "NHL Blades of Steel (USA).zip",
  "NHL Blades of Steel 2000 (USA).zip",
  "NSYNC - Get to the Show (USA).zip",
  "Nations, The - Land of Legends (Europe) (En,De).zip",
  "New Addams Family Series, The (Europe) (En,Fr,De,Es,It,Pt).zip",
  "New Adventures of Mary-Kate & Ashley, The (USA, Europe).zip",
  "New Batman Adventures, The - Chaos in Gotham (USA).zip",
  "Nicktoons Racing (USA).zip",
  "No Fear - Downhill Mountain Biking (Europe).zip",
  "Noddy and the Birthday Party (Europe) (En,Fr,De,Es).zip",
  "O'Leary Manager 2000 (Europe) (En,Fr,De,Es,It,Nl,Ca).zip",
  "Oddworld Adventures II (USA) (En,Fr,De,Es,It).zip",
  "Pac-Man - Special Color Edition (USA) (SGB Enhanced).zip",
  "Paperboy (USA, Europe).zip",
  "Papyrus (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Perfect Dark (USA, Europe) (En,Fr,De,Es,It) (Rumble Version).zip",
  "Pitfall - Beyond the Jungle (USA, Europe).zip",
  "Planet of the Apes (USA) (En,Fr,De,Es,It,Nl).zip",
  "Player Manager 2001 (Europe) (En,Fr).zip",
  "Pocket Bomberman (USA, Europe) (SGB Enhanced).zip",
  "Pocket Bowling (USA).zip",
  "Pocket Music (Europe) (En,Fr,De,Es,It).zip",
  "Pocket Racing (Europe).zip",
  "Pocket Soccer (Europe) (En,Fr,De,Es,It,Pt).zip",
  "Pokemon - Crystal Version (USA, Europe) (Rev A).zip",
  "Pokemon - Gold Version (USA, Europe) (SGB Enhanced).zip",
  "Pokemon - Silver Version (USA, Europe) (SGB Enhanced).zip",
  "Pokemon Pinball (USA) (Rumble Version) (SGB Enhanced).zip",
  "Pokemon Puzzle Challenge (USA).zip",
  "Pokemon Trading Card Game (USA) (SGB Enhanced).zip",
  "Polaris SnoCross (USA) (Rumble Version).zip",
  "Pong - The Next Level (USA, Europe).zip",
  "Pooh and Tigger's Hunny Safari (USA).zip",
  "Pop'n Pop (Europe).zip",
  "Portal Runner (USA).zip",
  "Power Quest (USA) (En,Fr,De,Es,It) (SGB Enhanced).zip",
  "Power Rangers - Lightspeed Rescue (USA, Europe).zip",
  "Power Rangers - Time Force (USA, Europe).zip",
  "Power Spike - Pro Beach Volleyball (USA).zip",
  "Powerpuff Girls, The - Bad Mojo Jojo (USA) (Rev B).zip",
  "Powerpuff Girls, The - Battle Him (USA) (Rev A).zip",
  "Powerpuff Girls, The - Paint the Townsville Green (USA) (Rev B).zip",
  "Prince Naseem Boxing (Europe) (En,Fr,De).zip",
  "Prince of Persia (USA, Europe) (En,Fr,De,Es,It).zip",
  "Pro Darts (USA).zip",
  "Pro Pool (USA) (En,Fr,De).zip",
  "Project S-11 (USA).zip",
  "Puchi Carat (Europe) (SGB Enhanced).zip",
  "Puzzle Master (USA).zip",
  "Puzzled (USA).zip",
  "Q-bert (USA).zip",
  "QIX Adventure (Europe).zip",
  "Quest - Fantasy Challenge (USA) (SGB Enhanced).zip",
  "Quest RPG - Brian's Journey (USA).zip",
  "Quest for Camelot (USA) (En,Fr,Es) (SGB Enhanced).zip",
  "R-Type DX (USA, Europe).zip",
  "Rainbow Islands (Europe) (En,Fr,De,Es,It).zip",
  "Rampage - World Tour (USA, Europe).zip",
  "Rampage 2 - Universal Tour (USA, Europe).zip",
  "Rampart (USA).zip",
  "Rats! (USA) (En,Es).zip",
  "Rayman (USA) (En,Fr,De,Es,It,Nl).zip",
  "Rayman 2 - The Great Escape (USA) (En,Fr,De,Es,It).zip",
  "Razor Freestyle Scooter (USA).zip",
  "Ready 2 Rumble Boxing (USA) (Rumble Version).zip",
  "Rescue Heroes - Fire Frenzy (USA).zip",
  "Resident Evil Gaiden (USA).zip",
  "Return of the Ninja (USA).zip",
  "Revelations - The Demon Slayer (USA) (SGB Enhanced).zip",
  "Rhino Rumble (USA, Europe).zip",
  "Rip-Tide Racer (Europe) (En,Fr,De,Es,It).zip",
  "Road Champs - BXS Stunt Biking (USA, Europe).zip",
  "Road Rash (USA, Europe).zip",
  "Roadsters Trophy (USA) (En,Fr,De,Es,It,Nl).zip",
  "Robin Hood (Europe) (En,Fr,De,Es,It,Nl).zip",
  "RoboCop (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Robopon - Sun Version (USA) (SGB Enhanced).zip",
  "Robot Wars - Metal Mayhem (Europe) (En,Fr,De,It,Nl,Sv).zip",
  "Rocket Power - Gettin' Air (USA, Europe).zip",
  "Rocky Mountain Trophy Hunter (USA).zip",
  "Roland Garros French Open (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Ronaldo V-Soccer (USA) (En,Fr,Es,Pt).zip",
  "Roswell Conspiracies - Aliens, Myths & Legends (USA) (En,Fr,De).zip",
  "Rox (USA, Europe).zip",
  "Rugrats - Time Travelers (USA, Europe).zip",
  "Rugrats - Totally Angelica (USA, Europe).zip",
  "Rugrats Movie, The (USA) (SGB Enhanced).zip",
  "Rugrats in Paris - The Movie (USA, Europe).zip",
  "SWIV (Europe) (En,Fr,De,Es,It).zip",
  "Sabrina - The Animated Series - Spooked! (USA, Europe).zip",
  "Sabrina - The Animated Series - Zapped! (USA, Europe).zip",
  "San Francisco Rush 2049 (USA, Europe).zip",
  "Santa Claus Junior (Europe).zip",
  "Scooby-Doo! - Classic Creep Capers (USA, Europe).zip",
  "Scrabble (Europe).zip",
  "Sesame Street Sports (USA).zip",
  "Sgt. Rock - On the Frontline (USA).zip",
  "Shadowgate Classic (USA, Europe) (En,Fr,De,Es,Sv) (Rev A).zip",
  "Shamus (USA, Europe).zip",
  "Shanghai Pocket (USA, Europe) (Rev A) (SGB Enhanced).zip",
  "Shantae (USA).zip",
  "Shaun Palmer's Pro Snowboarder (USA, Australia).zip",
  "Shrek - Fairy Tale Freakdown (USA, Europe) (En,Fr,De,Es,It).zip",
  "Simpsons, The - Night of the Living Treehouse of Horror (USA, Europe).zip",
  "Smurfs Nightmare, The (USA).zip",
  "Snoopy Tennis (USA) (En,Fr,Es).zip",
  "Snow White and the Seven Dwarfs (USA).zip",
  "Soccer Manager (Europe) (En,Fr,De,Es).zip",
  "Space Invaders (USA, Europe).zip",
  "Space Marauder (USA).zip",
  "Spacestation Silicon Valley (Europe) (En,Fr,De,Es,It,Nl,Sv).zip",
  "Spawn (USA).zip",
  "Speedy Gonzales - Aztec Adventure (USA, Europe).zip",
  "Spider-Man (USA, Europe).zip",
  "Spider-Man 2 - The Sinister Six (USA, Europe).zip",
  "Spirou Robbedoes - The Robot Invasion (Europe) (En,Fr,De,Es,It,Nl,Da).zip",
  "SpongeBob SquarePants - Legend of the Lost Spatula (USA, Europe).zip",
  "Spy vs. Spy (USA).zip",
  "Star Wars Episode I - Obi-Wan's Adventures (USA).zip",
  "Star Wars Episode I - Racer (USA, Europe) (Rumble Version).zip",
  "Street Fighter Alpha - Warriors' Dreams (USA).zip",
  "Stuart Little - The Journey Home (USA, Europe).zip",
  "Super Breakout! (USA).zip",
  "Super Mario Bros. Deluxe (USA, Europe) (Rev B).zip",
  "Supercross Freestyle (Europe) (En,Fr,De,Es,It).zip",
  "Survival Kids (USA) (SGB Enhanced).zip",
  "Suzuki Alstare Extreme Racing (Europe) (En,Fr,De,Es,It,Nl).zip",
  "TNN Outdoors Fishing Champ (USA) (SGB Enhanced).zip",
  "TOCA Touring Car Championship (USA, Europe).zip",
  "Tarzan (USA, Europe).zip",
  "Tazmanian Devil - Munching Madness (USA) (En,Fr,De,Es,It).zip",
  "Tech Deck Skateboarding (USA, Europe).zip",
  "Test Drive 2001 (USA).zip",
  "Test Drive 6 (USA).zip",
  "Test Drive Cycles (USA).zip",
  "Test Drive Le Mans (USA) (En,Fr,Es).zip",
  "Test Drive Off-Road 3 (USA) (Rumble Version) (SGB Enhanced).zip",
  "Tetris DX (World) (SGB Enhanced).zip",
  "Three Lions (Europe) (En,Fr,De,Es,It,Nl,Sv).zip",
  "Thunderbirds (Europe).zip",
  "Tiger Woods PGA Tour 2000 (USA, Europe).zip",
  "Tintin - Prisoners of the Sun (Europe) (En,Fr,De).zip",
  "Tintin in Tibet (Europe) (En,Fr,De,Es,It,Nl,Sv).zip",
  "Tiny Toon Adventures - Buster Saves the Day (USA).zip",
  "Tiny Toon Adventures - Dizzy's Candy Quest (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Titus the Fox to Marrakech and Back (USA).zip",
  "Tobu Tobu Girl Deluxe.zip",
  "Toki Tori (USA, Europe) (En,Ja,Fr,De,Es).zip",
  "Tom & Jerry (USA, Europe).zip",
  "Tom Clancy's Rainbow Six (USA, Europe) (En,Fr,De).zip",
  "Tom and Jerry - Mousehunt (USA) (En,Fr,Es).zip",
  "Tom and Jerry in Mouse Attacks! (USA).zip",
  "Tomb Raider (USA, Europe) (En,Fr,De,Es,It).zip",
  "Tomb Raider - Curse of the Sword (USA, Europe).zip",
  "Tonic Trouble (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Tonka Construction Site (USA).zip",
  "Tonka Raceway (USA) (Rumble Version).zip",
  "Tony Hawk's Pro Skater (USA, Europe).zip",
  "Tony Hawk's Pro Skater 2 (USA, Europe).zip",
  "Tony Hawk's Pro Skater 3 (USA, Europe).zip",
  "Toobin' (USA).zip",
  "Toonsylvania (USA).zip",
  "Tootuff (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Top Gear Pocket (USA) (Rumble Version).zip",
  "Top Gear Pocket 2 (USA).zip",
  "Top Gun - Fire Storm (USA, Europe) (En,Fr,De,Es,It,Nl).zip",
  "Total Soccer 2000 (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Towers - Lord Baniff's Deceit (USA, Europe).zip",
  "Toy Story 2 (USA, Europe) (SGB Enhanced).zip",
  "Toy Story Racer (USA, Europe).zip",
  "Trick Boarder (USA).zip",
  "Triple Play 2001 (USA, Europe).zip",
  "Trouballs (USA).zip",
  "Turok - Rage Wars (USA, Europe) (En,Fr,De,Es).zip",
  "Turok 2 - Seeds of Evil (USA, Europe) (En,Fr,De,Es).zip",
  "Turok 3 - Shadow of Oblivion (USA, Europe) (En,Fr,De,Es).zip",
  "Tweenies - Doodles' Bones (Europe) (En,De,Es,It).zip",
  "Tweety's High-Flying Adventure (USA).zip",
  "Tyco RC - Racin' Ratz (USA).zip",
  "UEFA 2000 (Europe) (En,Fr,De,Es,It,Nl).zip",
  "Ultimate Fighting Championship (USA).zip",
  "Ultimate Paint Ball (USA, Europe).zip",
  "Ultimate Surfing (USA).zip",
  "Uno (USA).zip",
  "V-Rally - Championship Edition (USA) (En,Fr,Es).zip",
  "VIP (USA, Europe) (En,Fr,De,Es,It).zip",
  "Vegas Games (USA).zip",
  "Vigilante 8 (USA) (Rumble Version).zip",
  "WCW Mayhem (USA, Europe).zip",
  "WWF Attitude (USA, Europe).zip",
  "WWF Betrayal (USA, Europe).zip",
  "WWF WrestleMania 2000 (USA, Europe).zip",
  "Wacky Races (USA) (En,Fr,Es).zip",
  "Walt Disney World Quest - Magical Racing Tour (USA, Europe).zip",
  "Wario Land 3 (World) (En,Ja).zip",
  "Wario Land II (USA, Europe) (SGB Enhanced).zip",
  "Warlocked (USA).zip",
  "Warriors of Might and Magic (USA) (En,Fr,De).zip",
  "Wendy - Every Witch Way (USA, Europe).zip",
  "Wetrix GB (Europe) (En,Fr,De).zip",
  "Who Wants to Be a Millionaire - 2nd Edition (USA).zip",
  "Wild Thornberrys, The - Rambler (USA).zip",
  "Wings of Fury (USA).zip",
  "Winnie the Pooh - Adventures in the 100 Acre Wood (USA).zip",
  "Woody Woodpecker (USA).zip",
  "Woody Woodpecker Racing (USA).zip",
  "World Destruction League - Thunder Tanks (USA) (En,Fr,De).zip",
  "Worms Armageddon (USA) (En,Fr,Es).zip",
  "X-Men - Mutant Academy (USA, Europe) (Rev A).zip",
  "X-Men - Mutant Wars (USA, Europe).zip",
  "X-Men - Wolverine's Rage (USA).zip",
  "Xena - Warrior Princess (USA, Europe) (En,Fr,De,Es,It,Nl).zip",
  "Xtreme Sports (USA).zip",
  "Xtreme Wheels (USA).zip",
  "Yars' Revenge (USA, Europe).zip",
  "Yoda Stories (USA, Europe).zip",
  "Yogi Bear - Great Balloon Blast (USA).zip",
  "Yu-Gi-Oh! - Dark Duel Stories (USA).zip",
  "Zebco Fishing! (USA) (Rumble Version).zip",
  "Zidane Football Generation (Europe) (En,Fr,De,Es,It).zip",
  "Zoboomafoo - Playtime in Zobooland (USA).zip"
];
export default games;